import font from '@ohos.font'

// 自定义字体注册
// export const registerFont = (name: string, srcPath:string)=> {
//   font.registerFont({
//     familyName: name,
//     familySrc: srcPath // font文件与pages目录同级
//   })
// }

// 统计几种字体,用于后序的规范
// @Styles function fontNormal () {
//   .fontWeight(FontWeight.Regular)
// }
//
// @Styles function fontMedium () {
//   .fontWeight(FontWeight.Medium)
// }
//
// @Styles function fontMedium () {
//   .fontWeight(FontWeight.Bold)
// }

export const aa = "aa"